"""Filename-derived reverse-search hints.

These helpers are intentionally conservative: they only decide whether a
branch that depends on a filename/source key has any useful key to try.  They
must never disable content-based reverse branches such as IQDB, SauceNAO or
TinEye, because generic Telegram/phone filenames can still match by pixels.
"""
from __future__ import annotations

import re
from pathlib import Path
from typing import Union

PathLike = Union[str, Path]

_HEX40_RE = re.compile(r"(?<![0-9a-fA-F])([0-9a-fA-F]{40})(?![0-9a-fA-F])")

# Names that are generated by Telegram/phones/browsers and do not carry a
# useful site key by themselves: photo_2022-..., video_2024-..., 1.jpg,
# 02.png, IMG_1234, Screenshot_..., VID_..., DSC_....  These names are not
# bad for pixel reverse search; they are only useless for filename-locator
# branches.
_GENERIC_STEM_PATTERNS = (
    re.compile(r"^photo_\d{4}[-_]\d{2}[-_]\d{2}(?:[ _-]\d{2}[-_]\d{2}[-_]\d{2})?$", re.I),
    re.compile(r"^video_\d{4}[-_]\d{2}[-_]\d{2}(?:[ _-]\d{2}[-_]\d{2}[-_]\d{2})?$", re.I),
    re.compile(r"^(?:img|vid|dsc|dscn|pict|screenshot|screen_shot|screen-shot)[ _-]?\d{2,}$", re.I),
    re.compile(r"^\d{1,4}$"),
    re.compile(r"^\d{1,3}[ _-]?\(\d+\)$"),
    re.compile(r"^copy(?:[ _-]?\d+)?$", re.I),
)


def _text_for_path(path: PathLike) -> tuple[str, str, str]:
    try:
        p = Path(path)
        return str(path or ""), p.name, p.stem
    except Exception:
        text = str(path or "")
        return text, text, text.rsplit(".", 1)[0]


def extract_rule34_40hex_key(path: PathLike) -> str:
    """Return a 40-hex rule34 image-key/SHA1-like token from a path, if any."""
    seen = set()
    for text in _text_for_path(path):
        for m in _HEX40_RE.findall(text or ""):
            key = str(m or "").lower()
            if key and key not in seen:
                return key
            seen.add(key)
    return ""


def is_generic_media_filename(path: PathLike) -> bool:
    """True when basename is a generated low-information media name."""
    _full, name, stem = _text_for_path(path)
    stem = str(stem or "").strip()
    if not stem:
        return True
    # A real 40hex key wins over the generic check.
    if extract_rule34_40hex_key(path):
        return False
    return any(rx.fullmatch(stem) for rx in _GENERIC_STEM_PATTERNS)


def filename_locator_bucket(path: PathLike) -> str:
    """Bucket for filename-only locator branches: key / generic / no_key."""
    if extract_rule34_40hex_key(path):
        return "key"
    if is_generic_media_filename(path):
        return "generic"
    return "no_key"
